services:
  web:
    build:
      context: docker/web
    container_name: order_web
    ports:
      - 80
    links:
      - app
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    container_name: order_app
    environment:
      PHP_IDE_CONFIG: "serverName=order"
      XDEBUG_CONFIG: client_host=172.17.0.1
    volumes:
      - ./:/var/www/html
      - ./docker/app/php/dev/opcache_dev.ini:/usr/local/etc/php/conf.d/opcache.ini
  mysql:
    build: ./docker/mysql
    container_name: order_mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 11111111
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    ports:
      - 3306

networks:
  default:
    name: order-backend
